<?php

/**
 * @file
 * Paragraph columns module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function par_section_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'par_section/section';
}


/**
 * Implements hook_theme().
 */
function par_section_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__paragraph_section' => [
      'base hook' => 'paragraph',
    ],
    'field__field_paragraph_extra_html' => [
      'base hook' => 'field',
    ],
  ];
}